### ISSUE TITLE
Is it possible to use this without Gradle or Maven?

### ISSUE THREAD

**Issue by SilverWolf32** [fwcd/atom-ide-kotlin#2]
Hello! I just installed this to get IDE support for Kotlin, and was greeted with a flood of project errors about "cannot access built-in declaration...ensure that you have a dependency on the Kotlin standard library".

I'm just building with make, and don't see the need for anything more complicated.

Is Gradle or Maven _required_ to use the language server? If so, how difficult would it be to remove that dependency?

**Comment by fwcd** [comment]
Already fixed in https://github.com/fwcd/kotlin-language-server/pull/154, but not released yet.

**Comment by SilverWolf32** [comment]
Ah, wonderful, thanks! I should've looked at the closed issues before opening this, sorry about that.
