### ISSUE TITLE
Having trouble installing "atom-ide-kotlin", please note I am a beginner in the field on programming.

### ISSUE THREAD

**Issue by Legendary-Person** [fwcd/atom-ide-kotlin#7]
C:\Windows\system32>apm uninstall ide-kotlin
Uninstalling ide-kotlin failed
Failed to delete ide-kotlin: No package.json found at C:\Users\KIIT\.atom\packages\ide-kotlin\package.json

C:\Windows\system32>apm install ide-kotlin
Installing ide-kotlin to C:\Users\KIIT\.atom\packages failed

> tree-sitter-kotlin@0.2.11 install C:\Users\KIIT\AppData\Local\Temp\apm-install-dir-20211111-6916-1lj7k9r.atkt\node_modules\ide-kotlin\node_modules\tree-sitter-kotlin
> node-gyp rebuild

C:\Users\KIIT\AppData\Local\Temp\apm-install-dir-20211111-6916-1lj7k9r.atkt\node_modules\ide-kotlin\node_modules\tree-sitter-kotlin>if not defined npm_config_node_gyp (node "C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\KIIT\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\KIIT\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\KIIT\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\KIIT\AppData\Local\Temp\apm-install-dir-20211111-6916-1lj7k9r.atkt\node_modules\ide-kotlin\node_modules\tree-sitter-kotlin
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\KIIT\AppData\Local\Temp\apm-install-dir-20211111-6916-1lj7k9r.atkt\package.json'
npm WARN apm-install-dir-20211111-6916-1lj7k9r.atkt No description
npm WARN apm-install-dir-20211111-6916-1lj7k9r.atkt No repository field.
npm WARN apm-install-dir-20211111-6916-1lj7k9r.atkt No README data
npm WARN apm-install-dir-20211111-6916-1lj7k9r.atkt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-kotlin@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter-kotlin@0.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KIIT\.atom\.apm\_logs\2021-12-11T07_53_26_921Z-debug.log

**Comment by sltodd** [comment]
Hi, I had the same troubles.  Maybe too late for this to be of help, but I made another package as this repo had too much going on: https://github.com/sltodd/kotlin-lsp-adapter

**Comment by fwcd** [comment]
Hey, could you check whether `ide-kotlin 0.6.8` fixes the issue for you?

**Comment by Legendary-Person** [comment]
I have switched to IntelliJ, however feel free to pin me in case this problem is solved.

**Comment by fwcd** [comment]
Since we no longer use `tree-sitter-kotlin` in the Atom extension (see ddff508461d42ff3b6949dccedae869de2a7364d), I will close this.
